require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  framework_script = 'Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh'
  next unless File.exist?(framework_script)

  script = File.read(framework_script)
  script.gsub!(
    'source="$(readlink "${source}")"',
    <<~'SH'.strip
    linked_source="$(readlink "${source}")"
    if [[ "${linked_source}" != /* ]]; then
      source="$(cd "$(dirname "${source}")" && realpath "${linked_source}")"
    else
      source="${linked_source}"
    fi
    SH
  )
  File.write(framework_script, script)
end
